name: Run .NET Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name:  Restore dependencies
      run: dotnet restore

    - name:  Build the solution
      run: dotnet build --no-restore

    - name: Run all tests (unitaires + intégration)
      run: dotnet test --no-build --verbosity normal

